ShieldSSO\Entity\AuthorizationCode:
  type: entity
  table: sso_oauth_authorization_code
  repositoryClass: ShieldSSO\Repository\AuthorizationCodeRepository

  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  fields:
    code:
      name: code
      type: string
      length: 255
      unique: true
      nullable: false
    expiryDateTime:
      name: expiry_date_time
      type: datetime
      nullable: false
    code:
      name: code
      type: string
      length: 255
      nullable: false
    revoked:
      name: revoked
      type: boolean
      nullable: false

  manyToOne:
    user:
      targetEntity: User
      inversedBy: authorizationCodes
      joinColumn:
        name: user_id
        referencedColumnName: id
    client:
      targetEntity: Client
      inversedBy: authorizationCodes
      joinColumn:
        name: client_id
        referencedColumnName: id

  manyToMany:
    scopes:
      targetEntity: Scope
      inversedBy: authorizationCodes
      joinTable:
        name: sso_oauth_authorization_code_scope
        joinColumns:
          authorization_code_id:
            referencedColumnName: id
        inverseJoinColumns:
          scope_id:
            referencedColumnName: id
