ShieldSSO\Entity\RefreshToken:
  type: entity
  table: sso_oauth_refresh_token
  repositoryClass: ShieldSSO\Repository\RefreshTokenRepository

  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  fields:
    code:
      name: code
      type: string
      length: 255
      unique: true
      nullable: false
    expiryDateTime:
      name: expiry_date_time
      type: datetime
      nullable: false
    revoked:
      name: revoked
      type: boolean
      nullable: false

  oneToOne:
    accessToken:
      targetEntity: AccessToken
      mappedBy: refreshToken
