ShieldSSO\Entity\User:
  type: entity
  table: sso_oauth_user
  repositoryClass: ShieldSSO\Repository\UserRepository

  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  fields:
    login:
      name: name
      type: string
      length: 255
      unique: true
      nullable: false
    active:
      name: active
      type: string
      length: 255
      nullable: true
    password:
      name: password
      type: string
      length: 255
      nullable: false

  oneToMany:
    accessTokens:
      targetEntity: AccessToken
      mappedBy: user
    authorizationCodes:
      targetEntity: AuthorizationCode
      mappedBy: user
